name: Discord Commit Webhook

on:
  push:
    branches:
      - main  # or whichever branch you want to track

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Fetch the secret value here
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          REPO_NAME="${{ github.repository }}"
          
          # Format the message to Discord
          MESSAGE="New commit to **$REPO_NAME**:\n- Commit message: '$COMMIT_MSG'\n- Author: $COMMIT_AUTHOR"
          
          # Send the message to Discord
          curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
